version: '3.0'

services:
  eth-agent:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        ETH_AGENT_GO_SRC_CT: ${ETH_AGENT_GO_SRC_CT}
        WORKDIR_CT: ${WORKDIR_CT}
    image: eth-agent
    container_name: eth-agent
    hostname: eth-agent
    restart: always
    ports:
      - ${ETH_AGENT_PORT}:${ETH_AGENT_PORT}
    volumes:
      - ${ETH_AGENT_LOG_VOLUME}:${ETH_AGENT_LOG_CT}
    depends_on:
      - redis  
      - mongo
    # command: [ "-e", "p", "-s", "all" ]

  redis:  
    image: redis:4.0-alpine
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_HOST_VOLUME}:/data  
    command: ["--requirepass","${REDIS_PASSWORD}"]  

  mongo:
    #image: mongo:3.6-jessie
    image: mongo:4.0-xenial
    container_name: mongo
    hostname: mongo
    restart: always
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_BART_DB=${MONGO_BART_DB}
      - MONGO_BART_USERNAME=${MONGO_BART_USERNAME}
      - MONGO_BART_PASSWORD=${MONGO_BART_PASSWORD}
      - MONGO_BART_READONLY_USERNAME=${MONGO_BART_READONLY_USERNAME}
      - MONGO_BART_READONLY_PASSWORD=${MONGO_BART_READONLY_PASSWORD}
      - MONGODB_HOST_VOL=${MONGODB_HOST_VOL}
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ${MONGODB_HOST_VOL}:/data/db
      - ./script/mongo-createuser.sh:/docker-entrypoint-initdb.d/mongo-createuser.sh
      #- ${MONGODB_HOST_VOL}/journal_0:/data/db/journal
    #   - ./mount_files/mongo.mongod.conf:/data/configdb/mongo.mongod.conf
    # command: ["mongod" ,"--config" ,"/data/configdb/mongo.mongod.conf"]
    command: ["mongod" ,"--auth"]
    # volumes_from:
    #   - mongodata
    # mongodata:
    #   image: tianon/true
    #   volumes:
    #     - ${MONGODB_HOST_VOL}:/data/db
    #     - ./mount_files/mongo.mongod.conf:/data/configdb/mongo.mongod.conf